// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2AzZaY0kCBmmwbSY3X-ieMSuqCmGsg68',
    appId: '1:726989396106:web:b1159151682e58b97f3573',
    messagingSenderId: '726989396106',
    projectId: 'seyahat-uygulamasi-68ff5',
    authDomain: 'seyahat-uygulamasi-68ff5.firebaseapp.com',
    storageBucket: 'seyahat-uygulamasi-68ff5.appspot.com',
    measurementId: 'G-TY2RV4YH9C',
    databaseURL: 'https://seyahat-uygulamasi-68ff5-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDncLjOASijkcM_CJKnEytk5DicyNqhoBE',
    appId: '1:726989396106:android:fa39cde3e7837e957f3573',
    messagingSenderId: '726989396106',
    projectId: 'seyahat-uygulamasi-68ff5',
    storageBucket: 'seyahat-uygulamasi-68ff5.appspot.com',
      databaseURL: 'https://seyahat-uygulamasi-68ff5-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrVR9v_Tm8zY7bmbjSf5zGm1ijpBeHEI8',
    appId: '1:726989396106:ios:e0b698c81c6a4a837f3573',
    messagingSenderId: '726989396106',
    projectId: 'seyahat-uygulamasi-68ff5',
    storageBucket: 'seyahat-uygulamasi-68ff5.appspot.com',
    iosClientId: '726989396106-t2jrf5dfas8b3ii5nm707dl9332pui5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthUi',
      databaseURL: 'https://seyahat-uygulamasi-68ff5-default-rtdb.firebaseio.com/'

  );
}
